-- 08_作品採点集計_適用SQL.sql
-- 目的:
-- - 作品ライブラリ、コンテスト応募、採点・集計基盤を追加
-- - 07_作品採点集計仕様.md の主要テーブル/制約を反映

begin;

-- ------------------------------------------------------------
-- Contests
-- ------------------------------------------------------------
create table if not exists public.contests (
  contest_id bigint generated by default as identity primary key,
  title varchar(100) not null,
  year int not null,
  status varchar(20) not null default 'draft'
    check (status in ('draft', 'accepting', 'primary_judging', 'final_judging', 'completed')),
  entry_start_at timestamptz not null,
  entry_end_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_contests_year on public.contests(year desc);
create index if not exists idx_contests_status on public.contests(status);

-- ------------------------------------------------------------
-- Works (作品ライブラリ)
-- ------------------------------------------------------------
create table if not exists public.works (
  work_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  title varchar(30) not null,
  category varchar(30) not null
    check (category in ('scratch', 'microbit', 'web_app', 'python', 'other')),
  has_hardware boolean not null default false,
  short_description varchar(100) not null,
  detailed_description text not null,
  work_url text not null,
  video_type varchar(20) not null check (video_type in ('youtube_url', 'mp4_file')),
  video_location text not null,
  thumbnail_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_works_user_id on public.works(user_id);
create index if not exists idx_works_updated_at on public.works(updated_at desc);

-- ------------------------------------------------------------
-- Contest Entries
-- ------------------------------------------------------------
create table if not exists public.contest_entries (
  entry_id bigint generated by default as identity primary key,
  contest_id bigint not null references public.contests(contest_id) on delete cascade,
  work_id uuid not null references public.works(work_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  work_number int not null check (work_number >= 100),
  entry_type varchar(10) not null default 'individual'
    check (entry_type in ('individual', 'team')),
  status varchar(30) not null default 'submitted'
    check (status in ('submitted', 'final_completed')),
  is_primary_passed boolean not null default false,
  created_at timestamptz not null default now(),
  constraint uq_contest_entries_contest_user unique (contest_id, user_id),
  constraint uq_contest_entries_contest_work_number unique (contest_id, work_number)
);

create index if not exists idx_contest_entries_contest on public.contest_entries(contest_id);
create index if not exists idx_contest_entries_primary_passed on public.contest_entries(contest_id, is_primary_passed);

-- ------------------------------------------------------------
-- Evaluations
-- ------------------------------------------------------------
create table if not exists public.evaluations (
  evaluation_id bigint generated by default as identity primary key,
  entry_id bigint not null references public.contest_entries(entry_id) on delete cascade,
  evaluator_id uuid not null references public.users(user_id) on delete cascade,
  phase varchar(20) not null check (phase in ('primary', 'final')),
  score_originality int not null check (score_originality between 1 and 5),
  score_skill int not null check (score_skill between 1 and 5),
  score_effort int not null check (score_effort between 1 and 5),
  score_purpose int not null check (score_purpose between 1 and 5),
  score_other numeric(2,1) not null check (score_other between 1.0 and 5.0),
  total_score numeric(3,1) not null check (total_score between 5.0 and 25.0),
  public_comment text null,
  private_comment text null,
  is_comment_published boolean not null default false,
  status varchar(30) not null default 'draft'
    check (status in ('draft', 'completed', 're_examine_required')),
  updated_at timestamptz not null default now(),
  constraint uq_evaluations_entry_evaluator_phase unique (entry_id, evaluator_id, phase)
);

create index if not exists idx_evaluations_entry on public.evaluations(entry_id);
create index if not exists idx_evaluations_phase_status on public.evaluations(phase, status);

-- ------------------------------------------------------------
-- Trigger: 更新時刻
-- ------------------------------------------------------------
create or replace function public.set_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_works_set_updated_at on public.works;
create trigger trg_works_set_updated_at
before update on public.works
for each row
execute function public.set_timestamp_updated_at();

drop trigger if exists trg_evaluations_set_updated_at on public.evaluations;
create trigger trg_evaluations_set_updated_at
before update on public.evaluations
for each row
execute function public.set_timestamp_updated_at();

-- ------------------------------------------------------------
-- Trigger: total_score 自動計算
-- ------------------------------------------------------------
create or replace function public.compute_evaluation_total_score()
returns trigger
language plpgsql
as $$
begin
  new.total_score := round((new.score_originality + new.score_skill + new.score_effort + new.score_purpose + new.score_other)::numeric, 1);
  return new;
end;
$$;

drop trigger if exists trg_evaluations_compute_total on public.evaluations;
create trigger trg_evaluations_compute_total
before insert or update on public.evaluations
for each row
execute function public.compute_evaluation_total_score();

-- ------------------------------------------------------------
-- RLS (必要に応じて有効化済み環境向けの最低限ポリシー)
-- 既存RLS運用に合わせて調整すること
-- ------------------------------------------------------------
alter table public.contests enable row level security;
alter table public.works enable row level security;
alter table public.contest_entries enable row level security;
alter table public.evaluations enable row level security;

-- contests: 全認証ユーザー参照可
drop policy if exists contests_select_authenticated on public.contests;
create policy contests_select_authenticated on public.contests
for select to authenticated
using (true);

-- works: 所有者のみ参照/更新/削除
drop policy if exists works_select_own on public.works;
create policy works_select_own on public.works
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists works_insert_own on public.works;
create policy works_insert_own on public.works
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists works_update_own on public.works;
create policy works_update_own on public.works
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists works_delete_own on public.works;
create policy works_delete_own on public.works
for delete to authenticated
using (auth.uid() = user_id);

-- contest_entries: 応募者は自分の行を参照/追加
drop policy if exists contest_entries_select_own on public.contest_entries;
create policy contest_entries_select_own on public.contest_entries
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists contest_entries_insert_own on public.contest_entries;
create policy contest_entries_insert_own on public.contest_entries
for insert to authenticated
with check (auth.uid() = user_id);

-- evaluations: 公開コメントのみ応募者に開示（参照）
drop policy if exists evaluations_select_published_comment_for_owner on public.evaluations;
create policy evaluations_select_published_comment_for_owner on public.evaluations
for select to authenticated
using (
  is_comment_published = true
  and exists (
    select 1
    from public.contest_entries ce
    where ce.entry_id = evaluations.entry_id
      and ce.user_id = auth.uid()
  )
);

commit;
